### ISSUE TITLE
'fileSystem' of null

### ISSUE THREAD

**Issue by vjandrei** [bradtraversy/ionreddit#2]
After npm install try to ionic serve it will give.
build dev failed: Cannot set property 'fileSystem' of null
The build folder gets only polyfills.js

**Comment by Antonio90** [comment]
Update your ionic app scripts to the latest version. It is 1.0.0 for RC5 release.

npm install @ionic/app-scripts@latest --save-dev

**Comment by moamen-ui** [comment]
After apply previous solution you've to rename src/app/main.dev.ts to main.ts

**Comment by aelsaman** [comment]
I made a pull request #3  to fix this issue. Thnx
